// Exports contract ABIs from the Foundry build into packages/abi/src/index.ts.
// Run `forge build` in contracts/ first.
import fs from "node:fs";
import path from "node:path";

const OUT = path.resolve("contracts/out");
const CONTRACTS = [
  "AssetRegistry", "PriceWall", "RedemptionVault", "SynthToken",
  "LaunchFactory", "LaunchHook", "LaunchRouter", "LaunchToken", "FeeEscrow", "BuybackVault", "LaunchLocker",
];

let src = "// Generated by scripts/export-abis.mjs. Do not edit.\n\n";
for (const name of CONTRACTS) {
  const file = path.join(OUT, `${name}.sol`, `${name}.json`);
  const { abi } = JSON.parse(fs.readFileSync(file, "utf8"));
  const id = name[0].toLowerCase() + name.slice(1) + "Abi";
  src += `export const ${id} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
fs.mkdirSync("packages/abi/src", { recursive: true });
fs.writeFileSync("packages/abi/src/index.ts", src);
console.log(`wrote ${CONTRACTS.length} ABIs to packages/abi/src/index.ts`);
